language: php
php:
  - '7.0'

env:
  - DB=sqlite

# Commands to be run before your environment runs.
before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev
  - mv .env.example .env
  - php artisan key:generate
  - touch storage/database.sqlite
  - php artisan migrate

# Commands you want to run that will verify your build.
script: phpunit